package sbnz.integracija;
import com.ftn.uns.ac.rs.hospitalapp.util.BloodData;
import com.ftn.uns.ac.rs.hospitalapp.beans.Alarm;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.lang.Double;
global ArrayList<Alarm> alarms;

rule "Rule designed for patient [ 152 ] - [ leukocytes] and [ erythrocytes] "
agenda-group "blood-data"
	when
		$data: BloodData((leukocytes <= 44.0 || leukocytes >= 55.0) && (erythrocytes <= 66.0 || erythrocytes >= 77.0), $val1: leukocytes,  $val2: erythrocytes,$id: patientID, $id == 152)
	then
	    alarms.add(new Alarm($id,"[ leukocytes ] ", $val1+"" , Double.valueOf($val1), new Date()));
	    alarms.add(new Alarm($id,"[ erythrocytes ] ", $val2+"" , Double.valueOf($val2), new Date()));
end;


