package sbnz.integracija;

import com.ftn.uns.ac.rs.hospitalapp.util.HeartMonitorData;
import com.ftn.uns.ac.rs.hospitalapp.beans.Alarm;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.lang.Double;

global ArrayList<Alarm> alarms;


rule " Not normal heart rate"
agenda-group "heartmonitor"
lock-on-active true
	when
		HeartMonitorData(heartRate <= 30 || heartRate >= 150, $heartRate: heartRate, $id: patientID)
	then
		System.out.println("Heart rate is not in normal range!");
		alarms.add(new Alarm($id,"Heart rate", Double.toString($heartRate) + " per minute", Double.valueOf($heartRate),new Date()));
end;


rule " Not normal systolic blood pressure"
agenda-group "heartmonitor"
lock-on-active true
	when
		HeartMonitorData(systolic <= 80 || systolic >= 196, $s:systolic, $d: diastolic,$id: patientID)
	then
	System.out.println("Systolic blood pressure is not in normal range!");
		alarms.add(new Alarm($id,"Systolic blood pressure", $d +"/"+ $s+" mm/Hg", Double.valueOf($s), new Date()));
end;

rule " Not normal diastolic blood pressure"
agenda-group "heartmonitor"
lock-on-active true
	when
		HeartMonitorData(diastolic <= 50 || diastolic >=130,$s:systolic, $d: diastolic, $id: patientID)
	then
	System.out.println("Diastolic blood pressure is not in normal range!");
		alarms.add(new Alarm($id,"Diastolic blood pressure",$d +"/"+ $s+" mm/Hg",Double.valueOf($d), new Date()));
end;

rule "Not normal saturation"
agenda-group "heartmonitor"
lock-on-active true
	when 
		HeartMonitorData(saturation <= 88, $id: patientID, $s: saturation);
	then
		System.out.println("Saturation is not in normal range!");
		alarms.add(new Alarm($id, "Saturation", $s + " %", Double.valueOf($s), new Date()));
end;