package sbnz.integracija;

import com.ftn.uns.ac.rs.hospitalapp.util.NeurologicalData;
import com.ftn.uns.ac.rs.hospitalapp.beans.Alarm;

import java.util.ArrayList;
import java.util.Date;
import java.lang.Double;

global ArrayList<Alarm> alarms;

rule "ICP not in normal range"
lock-on-active true
agenda-group "neuro-data"
when
	NeurologicalData($id: patientId, $icp: ICP, $icp < 5 || $icp > 15)
then
	System.out.println("Irregular ICP rule triggered");
	alarms.add(new Alarm($id, "ICP", Double.toString($icp) + " mm/Hg", $icp,new Date()));
end


rule "BIS not in normal range"
lock-on-active true
agenda-group "neuro-data"
when
	NeurologicalData($id: patientId, $bis: BIS, $bis <= 40)
then
	System.out.println("Irregular BIS rule triggered");
	alarms.add(new Alarm($id, "BIS", Double.toString($bis), $bis, new Date()));
end