package sbnz.events;
import com.ftn.uns.ac.rs.hospitalapp.beans.SecurityAlarm;
import java.util.ArrayList;
import java.util.Date;
global ArrayList<SecurityAlarm> alarms;

rule "Redefined log rule for log type [ fatal ]"
	agenda-group "logs"
	when
		$hl: HospitalLog(status == "fatal")
	then
		System.out.println("fatal"+" LOG OCCURED");
		alarms.add(new SecurityAlarm("", "fatal"+" LOG OCCURED", new Date()));
end


